### ISSUE TITLE
直接Postページを開いたあとにTopに戻れない

### ISSUE THREAD

**Issue by ikaruga777** [ikaruga777/ikaruga.org#103]
Postページをリロードしてからタイトル選択するとエラーになっちゃう。 https://github.com/ikaruga777/ikaruga.org/pull/102 でrouter-linkやめて解消したけどrouter-linkのままで運用したい〜。サーバー建てると再現しなくて、 `docs:build` で生成したときだけ再現する。

```
app.151bd136.js:6 TypeError: Cannot read properties of undefined (reading '_transitionClasses')
    at Array.fr (app.151bd136.js:6:44425)
    at F (app.151bd136.js:6:55606)
    at app.151bd136.js:6:55827
    at F (app.151bd136.js:6:56302)
    at Fn.__patch__ (app.151bd136.js:6:57437)
    at Fn.t._update (app.151bd136.js:6:34480)
    at Fn.r (app.151bd136.js:6:64899)
    at un.get (app.151bd136.js:6:26782)
    at un.run (app.151bd136.js:6:27666)
    at cn (app.151bd136.js:6:25774)
```

**Comment by ikaruga777** [comment]
https://github.com/ikaruga777/ikaruga.org/pull/102 で router-link やめて解決
